import "./globals.css";
import { Poppins } from "next/font/google";
import ProtectRoute from "@/components/ProtectRoute";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
    return (
        <html lang={params.lang}>
            <body className={`${poppins.className} mx-auto bg-white`}>
                <ProtectRoute />
                {children}
                <Toaster position="top-right" reverseOrder={false} />
            </body>
        </html>
    );
}
